### ISSUE TITLE
Basic source monitoring and recompiling framework

### ISSUE THREAD

**Issue by w23** [w23/cynth#1]
`inotifywait` on a single C source file.

**Comment by w23** [comment]
Done in commit 74509efb7df73235e03e94a3d245c89f655e74e8

**Comment by AntonBoch1244** [comment]
Issue lock would be needed in the future.

**Comment by w23** [comment]
what is 'issue lock'?

**Comment by AntonBoch1244** [comment]
Under participants, lock conversation button.
